# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - rubocop-minitest
  - rubocop-factory_bot
  - rubocop-rhino-project

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Rails:
  Enabled: true
  Exclude:
    - 'db/**/*'
  Include:
    - 'app/**/*'
    - 'config/**/*'

Minitest:
  Enabled: true

Performance:
  Enabled: true

RhinoProject:
  Enabled: true

Layout/LineLength:
  Max: 150

Lint/RedundantCopDisableDirective:
  Enabled: true

Rails/EnumSyntax:
  Enabled: true
  Include:
    - 'app/models/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Include:
    - 'app/**/*'
    - 'lib/**/*'
    - 'test/**/*'
